name: Validate Shipping Docs
on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - 'docs/shipping/**'
jobs:
  validate_docs_metadata:
    name: validate docs metadata
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: install dependencies
        run: pip install -r _metadata_validation/requirements.txt
      - name: Get changed files
        id: changed_files
        run: |
          PR_URL=$(jq -r .pull_request.url "$GITHUB_EVENT_PATH")
          FILES=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" $PR_URL/files | jq -r '[.[] | .filename] | join(",")')
          echo "CHANGED_FILES=$FILES" >> $GITHUB_ENV
      - name: Run validation
        env:
          FILES_TO_TRACK: ${{ env.CHANGED_FILES }}
        run: |
          python _metadata_validation/validate_metadata.py
          python_exit_code=$?
          if [ "$python_exit_code" -ne 0 ]; then
            echo "The validation script failed with exit code $python_exit_code."
            exit $python_exit_code
          fi